"""
ZOEY Study Assistant Skill

Comprehensive study and research workflow management:
- Connect to Google Colab/Notebook
- Manage study sessions and notes
- Research workflow automation
- Integration with external AI tools
- Citation and reference management
"""

import json
import os
import re
import time
import urllib.parse
import urllib.request
from datetime import datetime
from typing import Any


# =============================================================================
# Configuration & Constants
# =============================================================================

STUDY_DIR = os.path.expanduser("~/zoey_studies")
COLAB_BASE_URL = "https://colab.research.google.com"
NOTES_TEMPLATE = """# {title}

**Created:** {timestamp}
**Topic:** {topic}
**Source:** {source}

## Summary

{summary}

## Key Points

{key_points}

## Questions

{questions}

## Follow-up Actions

{actions}

---
*Generated by ZOEY Study Assistant*
"""


# =============================================================================
# Study Session Management
# =============================================================================

def start_study_session(args: dict) -> str:
    """Start a new study session with tracking."""
    topic = (args.get("topic") or "General Study").strip()
    goal = (args.get("goal") or "Learn and understand the topic").strip()
    duration = int(args.get("duration_minutes") or 0)
    
    os.makedirs(STUDY_DIR, exist_ok=True)
    
    session_id = f"study_{int(time.time())}_{re.sub(r'[^a-z0-9]', '_', topic.lower())[:30]}"
    session_file = os.path.join(STUDY_DIR, f"{session_id}.json")
    
    session_data = {
        "id": session_id,
        "topic": topic,
        "goal": goal,
        "started_at": datetime.now().isoformat(),
        "scheduled_duration": duration,
        "status": "active",
        "notes": [],
        "resources": [],
        "questions": [],
        "breakthroughs": [],
    }
    
    with open(session_file, "w", encoding="utf-8") as f:
        json.dump(session_data, f, indent=2)
    
    return (
        f"Started study session: **{topic}**\n"
        f"Goal: {goal}\n"
        f"Session ID: `{session_id}`\n"
        f"Type `pause study` to take a break, `end study` to finish."
    )


def add_study_note(args: dict) -> str:
    """Add a note to the current study session."""
    content = (args.get("content") or "").strip()
    note_type = (args.get("type") or "general").strip()
    source = (args.get("source") or "").strip()
    
    if not content:
        return "Please provide note content."
    
    # Find active session
    os.makedirs(STUDY_DIR, exist_ok=True)
    active_session = None
    session_file = None
    
    for fname in sorted(os.listdir(STUDY_DIR), reverse=True):
        if fname.startswith("study_") and fname.endswith(".json"):
            fpath = os.path.join(STUDY_DIR, fname)
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                if data.get("status") == "active":
                    active_session = data
                    session_file = fpath
                    break
            except Exception:
                continue
    
    if not active_session:
        return "No active study session. Start one with: study topic: [your topic]"
    
    note = {
        "timestamp": datetime.now().isoformat(),
        "type": note_type,
        "content": content,
        "source": source,
    }
    
    active_session["notes"].append(note)
    
    with open(session_file, "w", encoding="utf-8") as f:
        json.dump(active_session, f, indent=2)
    
    return f"Added {note_type} note to study session. Total notes: {len(active_session['notes'])}"


def end_study_session(args: dict) -> str:
    """End the current study session and generate summary."""
    summary_only = bool(args.get("summary_only"))
    
    os.makedirs(STUDY_DIR, exist_ok=True)
    active_session = None
    session_file = None
    
    for fname in sorted(os.listdir(STUDY_DIR), reverse=True):
        if fname.startswith("study_") and fname.endswith(".json"):
            fpath = os.path.join(STUDY_DIR, fname)
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                if data.get("status") == "active":
                    active_session = data
                    session_file = fpath
                    break
            except Exception:
                continue
    
    if not active_session:
        return "No active study session to end."
    
    # Calculate duration
    started = datetime.fromisoformat(active_session["started_at"])
    ended = datetime.now()
    duration = ended - started
    duration_mins = int(duration.total_seconds() / 60)
    
    active_session["status"] = "completed"
    active_session["ended_at"] = ended.isoformat()
    active_session["duration_minutes"] = duration_mins
    
    with open(session_file, "w", encoding="utf-8") as f:
        json.dump(active_session, f, indent=2)
    
    summary = f"""## Study Session Complete!

**Topic:** {active_session['topic']}
**Goal:** {active_session['goal']}
**Duration:** {duration_mins} minutes
**Notes Taken:** {len(active_session['notes'])}
**Resources:** {len(active_session['resources'])}

### Session saved to:
`{session_file}`

Use `review study` to see a summary or export your notes."""
    
    return summary


# =============================================================================
# Google Colab Integration
# =============================================================================

def open_colab(args: dict) -> str:
    """Open Google Colab with a notebook."""
    notebook_path = (args.get("notebook") or "").strip()
    new_notebook = bool(args.get("new", False))
    
    import tools
    
    if new_notebook or not notebook_path:
        # Open new empty Colab
        colab_url = f"{COLAB_BASE_URL}"
        tools.execute_tool("open_url", {"url": colab_url})
        return "Opening Google Colab with a new notebook."
    
    # Check if it's a GitHub notebook
    if "github.com" in notebook_path or notebook_path.endswith(".ipynb"):
        if "github.com" in notebook_path:
            # Convert GitHub URL to Colab format
            colab_url = notebook_path.replace("github.com", "github.com").replace("blob/", "")
            colab_url = f"https://colab.research.google.com/github/{colab_url.split('github.com/')[-1]}"
        else:
            colab_url = f"{COLAB_BASE_URL}/notebooks/{notebook_path}"
        
        tools.execute_tool("open_url", {"url": colab_url})
        return f"Opening notebook in Google Colab: {notebook_path}"
    
    # Local notebook - open Colab upload page
    tools.execute_tool("open_url", {"url": COLAB_BASE_URL})
    return f"Please upload your notebook to Colab. Local file: {notebook_path}"


def create_study_notebook(args: dict) -> str:
    """Create a new study notebook for a topic."""
    topic = (args.get("topic") or "Study Notes").strip()
    template = (args.get("template") or "study").strip()
    
    os.makedirs(STUDY_DIR, exist_ok=True)
    
    safe_topic = re.sub(r'[^a-z0-9]+', '_', topic.lower())[:30]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    notebook_name = f"study_{safe_topic}_{timestamp}.ipynb"
    notebook_path = os.path.join(STUDY_DIR, notebook_name)
    
    # Create notebook structure
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 4,
        "metadata": {
            "colab": {
                "name": topic,
                "provenance": [],
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3",
            },
        },
        "cells": [],
    }
    
    if template == "study":
        notebook["cells"] = [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# {topic}\n",
                    f"\n",
                    f"**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
                    f"\n",
                    f"## Learning Objectives\n",
                    f"\n",
                    f"1. \n",
                    f"2. \n",
                    f"3. \n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Research Notes\n",
                    "\n",
                    "### Key Concepts\n",
                    "\n",
                    "### Important Formulas\n",
                    "\n",
                    "### Examples\n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Code Practice\n",
                    "\n",
                    "```python\n",
                    "# Practice code here\n",
                    "```\n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Questions & Review\n",
                    "\n",
                    "**Questions:**\n",
                    "1. \n",
                    "2. \n",
                    "\n",
                    "**Summary:**\n",
                    "\n",
                ]
            },
        ]
    
    elif template == "research":
        notebook["cells"] = [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# Research: {topic}\n",
                    f"\n",
                    f"**Date:** {datetime.now().strftime('%Y-%m-%d')}\n",
                    f"\n",
                    f"## Research Question\n",
                    f"\n",
                    f"## Hypothesis\n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Literature Review\n",
                    "\n",
                    "| Source | Key Findings | Relevance |\n",
                    "|--------|--------------|-----------|\n",
                    "|        |              |           |\n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Data & Analysis\n",
                    "\n",
                    "```python\n",
                    "# Data analysis code\n",
                    "```\n",
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Conclusions\n",
                    "\n",
                    "## Future Work\n",
                ]
            },
        ]
    
    # Save notebook
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    
    return (
        f"Created new {template} notebook: **{notebook_name}**\n"
        f"Topic: {topic}\n"
        f"Path: `{notebook_path}`\n"
        f"\n"
        f"Open in Colab with: `open colab notebook: {notebook_path}`"
    )


# =============================================================================
# External AI Integration
# =============================================================================

def call_external_ai(args: dict) -> str:
    """Call an external AI service for specialized help."""
    service = (args.get("service") or "auto").lower()
    prompt = (args.get("prompt") or "").strip()
    context = (args.get("context") or "").strip()
    
    if not prompt:
        return "Please provide a prompt for the AI."
    
    # Build the full prompt with context
    full_prompt = prompt
    if context:
        full_prompt = f"Context:\n{context}\n\nTask:\n{prompt}"
    
    # Auto-select service based on prompt content
    if service == "auto":
        if any(k in prompt.lower() for k in ["code", "program", "debug", "function", "script"]):
            service = "github_copilot" if _check_copilot_available() else "openrouter"
        elif any(k in prompt.lower() for k in ["math", "equation", "calculate", "solve"]):
            service = "wolfram" if _check_wolfram_available() else "openrouter"
        elif any(k in prompt.lower() for k in ["image", "picture", "draw", "diagram"]):
            service = "dalle" if _check_dalle_available() else "openrouter"
        else:
            service = "openrouter"
    
    # Call appropriate service
    if service == "openrouter":
        return _call_openrouter(full_prompt, args)
    elif service == "claude":
        return _call_claude(full_prompt, args)
    elif service == "perplexity":
        return _call_perplexity(full_prompt, args)
    elif service == "wolfram":
        return _call_wolfram(prompt, args)
    else:
        return _call_openrouter(full_prompt, args)


def _call_openrouter(prompt: str, args: dict) -> str:
    """Call OpenRouter API."""
    import api
    
    try:
        client = api.make_client()
        messages = [
            {"role": "system", "content": "You are a helpful study and research assistant. Be concise but thorough."},
            {"role": "user", "content": prompt}
        ]
        
        model = args.get("model", "anthropic/claude-3.5-sonnet")
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=float(args.get("temperature", 0.7)),
            max_tokens=int(args.get("max_tokens", 2000))
        )
        
        return response.choices[0].message.content
    except Exception as e:
        return f"OpenRouter call failed: {e}"


def _call_claude(prompt: str, args: dict) -> str:
    """Call Anthropic Claude directly."""
    import os
    
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return "ANTHROPIC_API_KEY not set. Using OpenRouter fallback..."
    
    try:
        import requests
        
        headers = {
            "x-api-key": api_key,
            "content-type": "application/json",
        }
        
        data = {
            "model": args.get("model", "claude-3-5-sonnet-20241022"),
            "max_tokens": int(args.get("max_tokens", 2000)),
            "messages": [{"role": "user", "content": prompt}],
        }
        
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers=headers,
            json=data,
            timeout=60
        )
        
        if resp.status_code == 200:
            return resp.json()["content"][0]["text"]
        else:
            return f"Claude API error: {resp.status_code} - {resp.text}"
    except Exception as e:
        return f"Claude call failed: {e}"


def _call_perplexity(prompt: str, args: dict) -> str:
    """Call Perplexity API for research."""
    import os
    
    api_key = os.getenv("PERPLEXITY_API_KEY")
    if not api_key:
        return "PERPLEXITY_API_KEY not set. Using OpenRouter fallback..."
    
    try:
        import requests
        
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        data = {
            "model": args.get("model", "sonar-pro"),
            "messages": [
                {"role": "system", "content": "Be thorough and cite your sources."},
                {"role": "user", "content": prompt}
            ]
        }
        
        resp = requests.post(
            "https://api.perplexity.ai/chat/completions",
            headers=headers,
            json=data,
            timeout=60
        )
        
        if resp.status_code == 200:
            result = resp.json()
            content = result["choices"][0]["message"]["content"]
            # Include citations if available
            citations = result.get("citations", [])
            if citations:
                content += "\n\n**Sources:**\n" + "\n".join(f"- {c}" for c in citations[:5])
            return content
        else:
            return f"Perplexity API error: {resp.status_code}"
    except Exception as e:
        return f"Perplexity call failed: {e}"


def _call_wolfram(prompt: str, args: dict) -> str:
    """Call Wolfram Alpha for computational queries."""
    import os
    
    app_id = os.getenv("WOLFRAM_APP_ID")
    if not app_id:
        return "WOLFRAM_APP_ID not set. This is needed for math/computation queries."
    
    try:
        import urllib.parse
        import urllib.request
        
        query = urllib.parse.quote(prompt)
        url = f"http://api.wolframalpha.com/v2/query?input={query}&appid={app_id}&format=plaintext&output=json"
        
        with urllib.request.urlopen(url, timeout=30) as response:
            data = json.loads(response.read().decode())
        
        if data.get("queryresult", {}).get("success"):
            pods = data["queryresult"].get("pods", [])
            results = []
            for pod in pods[:3]:
                title = pod.get("title", "")
                subpods = pod.get("subpods", [])
                for sub in subpods:
                    text = sub.get("plaintext", "")
                    if text:
                        results.append(f"**{title}:** {text}")
                        break
            return "\n\n".join(results) if results else "No results found."
        else:
            return "Wolfram Alpha couldn't process that query. Try rephrasing your math/computation question."
    except Exception as e:
        return f"Wolfram Alpha error: {e}"


def _check_copilot_available() -> bool:
    """Check if GitHub Copilot CLI is available."""
    try:
        import subprocess
        result = subprocess.run(["gh", "copilot", "--version"], capture_output=True, text=True)
        return result.returncode == 0
    except Exception:
        return False


def _check_wolfram_available() -> bool:
    """Check if Wolfram Alpha is configured."""
    import os
    return bool(os.getenv("WOLFRAM_APP_ID"))


def _check_dalle_available() -> bool:
    """Check if DALL-E is configured."""
    import os
    return bool(os.getenv("OPENAI_API_KEY"))


# =============================================================================
# Research Workflow Automation
# =============================================================================

def deep_research(args: dict) -> str:
    """
    Multi-step research workflow:
    1. Search for current information
    2. Call external AI for synthesis
    3. Generate structured notes
    """
    query = (args.get("query") or "").strip()
    depth = (args.get("depth") or "medium").lower()
    save = bool(args.get("save", True))
    
    if not query:
        return "Please provide a research query."
    
    os.makedirs(STUDY_DIR, exist_ok=True)
    
    # Step 1: Web search for current info
    try:
        from research_skill import research_topic
        search_results = research_topic({"topic": query, "max_results": 5 if depth == "shallow" else 10})
    except Exception as e:
        search_results = f"Search error: {e}"
    
    # Step 2: Call external AI for synthesis
    synthesis_prompt = f"""Research Query: {query}

Search Results:
{search_results[:3000]}

Please provide:
1. A concise summary of the topic (3-5 sentences)
2. Key findings or main points (bullet points)
3. Important technical details or data
4. Related concepts to explore
5. Any uncertainties or areas needing more research

Format for a study note."""

    synthesis = _call_openrouter(synthesis_prompt, {"max_tokens": 1500})
    
    # Step 3: Generate structured notes
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_query = re.sub(r'[^a-z0-9]+', '_', query.lower())[:30]
    note_path = os.path.join(STUDY_DIR, f"research_{safe_query}_{timestamp}.md")
    
    note_content = f"""# Research: {query}

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Depth:** {depth}
**Query:** {query}

## Summary

{synthesis}

## Raw Search Results

```
{search_results}
```

## Next Steps

- [ ] Review and verify key findings
- [ ] Cross-reference with additional sources
- [ ] Integrate into main study notes

---
*Generated by ZOEY Deep Research*
"""
    
    if save:
        with open(note_path, "w", encoding="utf-8") as f:
            f.write(note_content)
        result_msg = f"Research complete! Saved to: `{note_path}`"
    else:
        result_msg = "Research complete! (not saved)"
    
    return (
        f"{result_msg}\n\n"
        f"**Query:** {query}\n"
        f"**Synthesis Preview:**\n{synthesis[:500]}...\n\n"
        f"Use `export study notes` to save to a different format."
    )


def export_study_notes(args: dict) -> str:
    """Export study notes to various formats."""
    session_id = (args.get("session") or "").strip()
    format_type = (args.get("format") or "markdown").lower()
    
    if not session_id:
        return "Please specify a study session ID."
    
    # Find the session
    session_file = os.path.join(STUDY_DIR, f"{session_id}.json")
    if not os.path.exists(session_file):
        return f"Study session not found: {session_id}"
    
    with open(session_file, "r", encoding="utf-8") as f:
        session = json.load(f)
    
    if format_type == "markdown":
        return _export_to_markdown(session)
    elif format_type == "anki":
        return _export_to_anki(session)
    elif format_type == "pdf":
        return _export_to_pdf(session)
    else:
        return f"Unsupported format: {format_type}. Use: markdown, anki, or pdf."


def _export_to_markdown(session: dict) -> str:
    """Export session to a formatted markdown file."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{session['id']}_{timestamp}.md"
    filepath = os.path.join(STUDY_DIR, filename)
    
    lines = [
        f"# Study Notes: {session['topic']}",
        "",
        f"**Goal:** {session['goal']}",
        f"**Started:** {session['started_at']}",
        f"**Duration:** {session.get('duration_minutes', 'N/A')} minutes",
        "",
        "---",
        "",
        "## Session Notes",
        "",
    ]
    
    for note in session.get("notes", []):
        lines.append(f"### {note['type'].upper()} - {note['timestamp']}")
        if note.get('source'):
            lines.append(f"**Source:** {note['source']}")
        lines.append("")
        lines.append(note['content'])
        lines.append("")
    
    lines.extend([
        "---",
        "",
        "## Resources Used",
        "",
    ])
    
    for resource in session.get("resources", []):
        lines.append(f"- {resource}")
    
    lines.extend([
        "",
        "---",
        "",
        "*Generated by ZOEY Study Assistant*",
    ])
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    return f"Exported to: `{filepath}`"


def _export_to_anki(session: dict) -> str:
    """Export notes to Anki flashcard format."""
    lines = ["#separator:Tab", "#html:false", "#tags:zoey_study"]
    
    for note in session.get("notes", []):
        if note['type'] in ['question', 'key_point', 'definition']:
            # Front: Question/Key point, Back: Answer/Explanation
            front = note['content'][:200]
            back = note.get('source', 'Review your notes for the full answer.')
            lines.append(f'{front}\t{back}')
    
    filename = f"{session['id']}_anki.txt"
    filepath = os.path.join(STUDY_DIR, filename)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    return f"Anki deck exported to: `{filepath}`\nImport in Anki: File → Import → select this file."


def _export_to_pdf(session: dict) -> str:
    """Export session to PDF."""
    try:
        from weasyprint import HTML, CSS
        
        # Create HTML content
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                h1 {{ color: #333; border-bottom: 2px solid #666; }}
                h2 {{ color: #555; margin-top: 30px; }}
                .meta {{ color: #666; font-style: italic; }}
                .note {{ background: #f5f5f5; padding: 10px; margin: 10px 0; border-left: 3px solid #666; }}
            </style>
        </head>
        <body>
            <h1>Study Notes: {session['topic']}</h1>
            <p class="meta">Goal: {session['goal']}</p>
            <p class="meta">Started: {session['started_at']}</p>
            <p class="meta">Duration: {session.get('duration_minutes', 'N/A')} minutes</p>
            
            <h2>Session Notes</h2>
        """
        
        for note in session.get("notes", []):
            html_content += f"""
            <div class="note">
                <strong>{note['type'].upper()}</strong> - {note['timestamp']}<br>
                {note['content'][:500]}
            </div>
            """
        
        html_content += """
        </body>
        </html>
        """
        
        filename = f"{session['id']}.pdf"
        filepath = os.path.join(STUDY_DIR, filename)
        
        HTML(string=html_content).write_pdf(filepath)
        
        return f"PDF exported to: `{filepath}`"
        
    except ImportError:
        return "PDF export requires 'weasyprint'. Install with: pip install weasyprint"
    except Exception as e:
        return f"PDF export failed: {e}"


# =============================================================================
# Tool Definitions for Integration
# =============================================================================

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "start_study_session",
            "description": "Start a new study session with tracking and goal-setting.",
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {"type": "string", "description": "The topic or subject to study."},
                    "goal": {"type": "string", "description": "What you want to achieve in this session."},
                    "duration_minutes": {"type": "integer", "description": "Optional target duration in minutes."},
                },
                "required": ["topic"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "add_study_note",
            "description": "Add a note to the current active study session.",
            "parameters": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "The note content."},
                    "type": {"type": "string", "description": "Note type: general, question, key_point, definition, example."},
                    "source": {"type": "string", "description": "Optional source URL or reference."},
                },
                "required": ["content"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "end_study_session",
            "description": "End the current study session and generate a summary.",
            "parameters": {
                "type": "object",
                "properties": {
                    "summary_only": {"type": "boolean", "description": "If true, only show summary without ending session."},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "open_colab",
            "description": "Open Google Colab with a notebook (new or existing).",
            "parameters": {
                "type": "object",
                "properties": {
                    "notebook": {"type": "string", "description": "Path to notebook or GitHub URL. Leave empty for new notebook."},
                    "new": {"type": "boolean", "description": "Open a new empty notebook."},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "create_study_notebook",
            "description": "Create a new Jupyter notebook for studying a topic.",
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {"type": "string", "description": "The topic/title of the notebook."},
                    "template": {"type": "string", "description": "Template type: study, research, code."},
                },
                "required": ["topic"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "deep_research",
            "description": "Multi-step research: search web, call AI for synthesis, save structured notes.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Research question or topic."},
                    "depth": {"type": "string", "description": "shallow, medium, or deep research."},
                    "save": {"type": "boolean", "description": "Save results to file."},
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "call_external_ai",
            "description": "Call an external AI service (Claude, Perplexity, etc.) for specialized help.",
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "description": "AI service: openrouter, claude, perplexity, wolfram, or auto."},
                    "prompt": {"type": "string", "description": "The task/prompt for the AI."},
                    "context": {"type": "string", "description": "Additional context from previous research."},
                    "model": {"type": "string", "description": "Specific model to use (optional)."},
                },
                "required": ["prompt"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "export_study_notes",
            "description": "Export study notes to various formats (markdown, Anki, PDF).",
            "parameters": {
                "type": "object",
                "properties": {
                    "session": {"type": "string", "description": "Session ID to export."},
                    "format": {"type": "string", "description": "Format: markdown, anki, or pdf."},
                },
                "required": ["session", "format"],
            },
        },
    },
]


# =============================================================================
# Dispatch for Tool Integration
# =============================================================================

DISPATCH = {
    "start_study_session": start_study_session,
    "add_study_note": add_study_note,
    "end_study_session": end_study_session,
    "open_colab": open_colab,
    "create_study_notebook": create_study_notebook,
    "deep_research": deep_research,
    "call_external_ai": call_external_ai,
    "export_study_notes": export_study_notes,
}


# =============================================================================
# Helper Functions for External AI Selection
# =============================================================================


def get_ai_recommendation(query: str) -> str:
    """Recommend which AI service to use based on query type."""
    query_lower = query.lower()
    
    # Math/Computation
    if any(k in query_lower for k in [
        "calculate", "solve", "equation", "integral", "derivative",
        "formula", "math", "algebra", "geometry", "statistics"
    ]):
        return "wolfram"
    
    # Research/Facts
    if any(k in query_lower for k in [
        "research", "what is", "how does", "explain", "compare",
        "difference between", "history of", "latest", "news"
    ]):
        return "perplexity"
    
    # Code/Programming
    if any(k in query_lower for k in [
        "code", "program", "debug", "function", "script",
        "python", "javascript", "error", "fix"
    ]):
        return "claude"
    
    # Images/Creatives
    if any(k in query_lower for k in [
        "image", "picture", "diagram", "draw", "create visual"
    ]):
        return "dalle"
    
    # Default
    return "openrouter"


# =============================================================================
# Main Interface
# =============================================================================

if __name__ == "__main__":
    # Test mode
    print("ZOEY Study Assistant Test Mode")
    print("=" * 50)
    
    # Test study session
    print("\n1. Testing study session...")
    result = start_study_session({
        "topic": "Machine Learning",
        "goal": "Understand neural networks",
        "duration_minutes": 60
    })
    print(result)
    
    # Test note adding
    print("\n2. Testing add note...")
    result = add_study_note({
        "content": "Neural networks are composed of layers of perceptrons.",
        "type": "key_point",
        "source": "Deep Learning Book"
    })
    print(result)
    
    # Test research
    print("\n3. Testing deep research...")
    result = deep_research({
        "query": "attention mechanism in transformers",
        "depth": "medium",
        "save": False
    })
    print(result[:500] + "...")
